# ?? ??
server.port=8080

# DB ??
spring.datasource.url=jdbc:mysql://localhost:3306/b201_dev?serverTimezone=Asia/Seoul
spring.datasource.username=nyoung
spring.datasource.password=Whgusuddl153!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ????
spring.profiles.active=dev